### ISSUE TITLE
docker版无法播放音乐

### ISSUE THREAD

**Issue by usc** [foamzou/melody#19]
附日志：

```

ℹ -------
ℹ searchSong with {"0":{"keyword":"光辉岁月"}}
ℹ cmdStr: /app/backend/src/service/media_fetcher/../../../bin/media-get -k "光辉岁月" --searchType="song" -m --infoFormat=json -l silence
ℹ -------
ℹ 0
ℹ -------
ℹ getMetaWithUrl from https://www.kuwo.cn/play_detail/19534401

 ERROR  exec error: Error: Command failed: /app/backend/src/service/media_fetcher/../../../bin/media-get -u "https://www.kuwo.cn/play_detail/19534401" -m --infoFormat=json
panic: invalid character 'æ' looking for beginning of value

goroutine 1 [running]:
main.main()
	command-line-arguments/main.go:24 +0xd0


ℹ -------
ℹ 2
ℹ Command failed: /app/backend/src/service/media_fetcher/../../../bin/media-get -u "https://www.kuwo.cn/play_detail/19534401" -m --infoFormat=json
panic: invalid character 'æ' looking for beginning of value

goroutine 1 [running]:
main.main()
	command-line-arguments/main.go:24 +0xd0

ℹ -------

 ERROR  getMetaWithUrl failed with https://www.kuwo.cn/play_detail/19534401, err: Command failed: /app/backend/src/service/media_fetcher/../../../bin/media-get -u "https://www.kuwo.cn/play_detail/19534401" -m --infoFormat=json
panic: invalid character 'æ' looking for beginning of value

goroutine 1 [running]:
main.main()
	command-line-arguments/main.go:24 +0xd0

```

**Comment by foamzou** [comment]
你应该是使用了境外 IP 访问（可以考虑不要全局代理，试试走 PAC？部署在国外 VPS 的话，目前无解），返回非预期的报文，我没做处理，就会报这个错。国内音乐平台有限制 IP。
我后面看怎么做个代理功能。

**Comment by foamzou** [comment]
#58
